### ISSUE TITLE
Abgabe am 19.11.2017 (System Requirements zu unserem tex-Dokument hinzufügen)

### ISSUE THREAD

**Issue by rkleee** [rkleee/seGruppeH#2]
- [ ] Introduction/Vorwort umschreiben (gekürzte Übersetzung)
- [x] Mind. 1 Diagramm hinzufügen
- [x] Insg. 3 Szenarios hinzufügen (z.B. User registriert sich. Was kann schief gehen? Was passiert bei Erfolg?)
- [x] Mind. 3 Szenarios (beispielhafte Vorgänge) beschreiben (Was sollte passieren, was könnte schief gehen, was sollte passieren, wenn es schief geht, wie ist der Zustand nach Ende des Vorgangs)
- [x] User Requirements mit der Musterlösung vergleichen und daraus je mind. 1 System Requirement erstellen.

**Comment by curala70** [comment]
Introduction haben wir aus der Musterlösung kopiert und lassen wir auf Englisch... Ist auch ok so.
